### PR TITLE
Stage react api

### PR DESCRIPTION
**Pull request by kltrmtz**
1st Submit

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Thank you for sending your code for review! It looks good in general, but it will require some bug fixing. Most issues regard responsive layout. Please find issues listed below. I hope they will be easy to fix!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Page content should be centered
* A redundant white line at the top of the header: https://snipboard.io/zsYw8r.jpg
* Links in footer have incorrect styles
* Please check font families in popups
* saved-news looks incorrectly: https://snipboard.io/xN6z2g.jpg
* Please check styles of `card__source`

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Pages with news-cards rendered scroll **on all screens**, including desktop
* Home page without search results scrolls on 687 and smaller, 948 - 1024
* saved-news scrolls on all screens

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should open in new tabs
* Please add some sample cards to saved-news so I can check the layout.

- [ ]  Classes are named according to BEM specifications.

* Elements can't be used outside of their blocks: `main__content`, `register__modal`, other similar cases
* Similar entities, that need the same styles, need the same class names: links in header, links in footer.


- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` should be in nav, ul or ul inside nav.
* `card` should be article, not section.
* `about__paragraph` - please don't use br inside a paragraph. The text in `about` contains two paragraphs, semantically, you need to remove br and use two `<p>`
* `footer__copyright` should be a paragraph
* `register__modal-heading` should be a heading

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.

* Sign In link on Register Successful modal should open "Sign In" modal

- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [ ] A `components` folder with JS and CSS files for the components.
  * Each component needs its own folder with jsx and css for it: https://snipboard.io/HtjU74.jpg
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* hover state of "Show more" button is missing
* active state of "Search" button is missing

- [ ]  The design reuses components wherever possible.

* All modal windows can use the same component

- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

Please, use raster graphics format for photos in a gallery, backgrounds and other content pictures (jpg or png). Vector graphics is necessary for icons and logos, pictures (often with transparent background) which need to be flexible and scalable. For content pictures of the page, where we need a vast color shading and depth variation, it's a good practice to use raster graphics.

https://designshack.net/articles/layouts/vector-vs-raster-what-do-i-use/

## Number of points: 38

**Comment by ImaliaNsk** [comment]
Thank you for the corrections, they look great! The pages look much better on intermediate resolutions. However, it requires further refactoring.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Page content should be centered
* Cards are too narrow on 320: https://snipboard.io/zbNdTy.jpg
* saved-news looks incorrectly: https://snipboard.io/W6Y0Dq.jpg https://snipboard.io/FsOyqG.jpg

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://snipboard.io/YGzu5E.jpg The layout is not responsive
* https://snipboard.io/I3j46y.jpg All cards should be the same width and height

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Please add some sample cards to saved-news so I can check the layout.

- [ ]  Classes are named according to BEM specifications.

* Elements without their blocks: `register__modal` and other

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* No need to nest section inside another section: https://snipboard.io/DHNQOf.jpg

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* hover state of "Show more" button is missing
* active state of "Search" button is missing

- [ ]  The design reuses components wherever possible.

* All modal windows can use the same component

- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

Please, use raster graphics format for photos in a gallery, backgrounds and other content pictures (jpg or png). Vector graphics is necessary for icons and logos, pictures (often with transparent background) which need to be flexible and scalable. For content pictures of the page, where we need a vast color shading and depth variation, it's a good practice to use raster graphics.

https://designshack.net/articles/layouts/vector-vs-raster-what-do-i-use/

## Number of points: 52

**Comment by kltrmtz** [comment]
Sample Cards are in utils, folder api.js.

**Comment by ImaliaNsk** [comment]
Thanks for the fixes, the project has been significantly improved! Responsive layout looks much better 👍 A few more issues are required to fix, however.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* Please remove all red borders
* Text is cards should be hidden with ellipsis, not just cropped (home page, cards in saved-cards look great)

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Source text is cropped: https://snipboard.io/P9M2xh.jpg

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* Elements without their blocks: `header__saved`, `saved__news` and other

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* https://snipboard.io/lFYQIa.jpg

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.

* All modal windows can use the same component

- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by kltrmtz** [comment]
Thank you for the continued review help!! I thought I addressed a few issues.. I changed some images to png & svg, assuming that would help optimize the vector & raster. Any additional details on my errors is very appreciated.

**Comment by ImaliaNsk** [comment]
You did a great job with corrections! The project is accepted, and I wish you success on the next stage and in your future projects!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* Elements without their blocks: `header__saved`, `article__content` and other

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.

* All modal windows can use the same component

- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

* It's better to reduce size of images. Use the optimized images to save bandwidth and faster loading time of your website. You can use online-compression service, e.g. [https://tinypng.com](https://tinypng.com/)

## Number of points: 92

**Pull request merged**
